default: &default
  adapter: postgresql
  encoding: unicode
  pool: "25"
  url: "postgres_development"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
