default: &default
  adapter: postgresql
  encoding: unicode
  pool: "25"
  url: "postgres_development"

development:
  primary:
    <<: *default
    database: <%= ActiveModel::Type::Boolean.new.cast(ENV["DISABLED"]) ? "development_primary" : "development" %>

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
