# frozen_string_literal: true

require_relative "../base"

module Exceptions
  module ActiveRecord
    module Postgresql
      class UndefinedColumn < Base
        private

        def can_correct?
          corrected_word.present?
        end

        def unknown_from_exception
          exception.to_s.match(exception_regexp)[1]
        end

        def corrected_word
          match = exception.to_s.match(hint_regexp)
          return if match.nil?

          match[1].split(".").last
        end

        # The not found column name
        def exception_regexp
          /column \w+\.(\w+)\s/
        end

        # The hint generated by PG
        def hint_regexp
          /"(\w+\.\w+)"/
        end
      end
    end
  end
end
